### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by AlexanderLiuckanov** [cbaerike/MySQL-Backup-Manager#13]
Hello Team,

I had a little problem to Backup DataBase with size 420MB

2015-12-19 10:40 - ERROR - Unknown exception occurred during backup: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StreamReader.ReadToEnd()
   at MySQLBackup.Application.Backup.MySQLDumpProcess.ProcessMySqlDump(Guid databaseId)

**Comment by cbaerike** [comment]
Hi Alexander,

Which version have you tried for this? the 1.4.4 Hotfix release was supposed to address this issue: https://github.com/cbaerike/MySQL-Backup-Manager/releases/tag/v.1.4.4-Hotfix
