### ISSUE TITLE
System.ComponentModel.Win32Exception (0x80004005)

### ISSUE THREAD

**Issue by davouch** [cbaerike/MySQL-Backup-Manager#15]
Hi everyone,

I seem I can't get my MySQL Backup Manager 1.4.4 running. The system refuses to execute a backup and consistently shows the following message in the log. Is there anything I could be doing wrong, or is this possibly a bug.

I'm running a 32bit W7 Pro.

Thanks a lot for any advice.
David

```
2016-02-02 11:59 - ERROR - Unknown exception occurred during backup: System.ComponentModel.Win32Exception (0x80004005): Systém nemůže nalézt uvedený soubor
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MySQLBackup.Application.Backup.MySQLDumpProcess.ProcessMySqlDump(Guid databaseId)
```

The Czech sentence "Systém nemůže nalézt uvedený soubor" says: "Systém cannot find the specified file."

**Comment by cbaerike** [comment]
Hi David,

This error means that the system could not find the MySQLDump.exe file. Please add the MySQL \bin path to your system's PATH variable and try again.

**Comment by davouch** [comment]
Thanks, cbaerike.
David
